-- Таблица пользователей
CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(250) NOT NULL,
    email VARCHAR(254) NOT NULL UNIQUE
);

-- Таблица категорий
CREATE TABLE IF NOT EXISTS categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE
);

-- Таблица событий (Location встроена как lat/lon)
CREATE TABLE IF NOT EXISTS events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    annotation VARCHAR(2000) NOT NULL,
    category_id BIGINT NOT NULL REFERENCES categories(id),
    confirmed_requests BIGINT DEFAULT 0,
    created_on TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    description VARCHAR(7000) NOT NULL,
    event_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    initiator_id BIGINT NOT NULL REFERENCES users(id),
    lat FLOAT NOT NULL,
    lon FLOAT NOT NULL,
    paid BOOLEAN NOT NULL DEFAULT FALSE,
    participant_limit INT DEFAULT 0,
    published_on TIMESTAMP WITHOUT TIME ZONE,
    request_moderation BOOLEAN DEFAULT TRUE,
    state VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    title VARCHAR(120) NOT NULL,
    views BIGINT DEFAULT 0,
    moderation_note VARCHAR(1000)
);

-- Совместимость со старыми БД: добавляем колонку модерации, если она отсутствует
ALTER TABLE events ADD COLUMN IF NOT EXISTS moderation_note VARCHAR(1000);

-- Таблица заявок на участие
CREATE TABLE IF NOT EXISTS participation_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT NOT NULL REFERENCES events(id) ON DELETE CASCADE,
    requester_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    created TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING'
);

-- Таблица комментариев к событиям
CREATE TABLE IF NOT EXISTS comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text VARCHAR(2000) NOT NULL,
    event_id BIGINT NOT NULL REFERENCES events(id) ON DELETE CASCADE,
    author_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    created_on TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_on TIMESTAMP WITHOUT TIME ZONE,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    moderation_note VARCHAR(1000)
);

-- Подписки пользователей
CREATE TABLE IF NOT EXISTS subscriptions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    follower_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    following_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    created_on TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT uq_subscription_follower_following UNIQUE (follower_id, following_id)
);

-- Рейтинг событий (лайки/дизлайки)
CREATE TABLE IF NOT EXISTS event_ratings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT NOT NULL REFERENCES events(id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    vote VARCHAR(20) NOT NULL,
    created_on TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_on TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT uq_event_rating_user_event UNIQUE (user_id, event_id)
);

-- Управляемые локации (администрирование)
CREATE TABLE IF NOT EXISTS managed_locations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL UNIQUE,
    lat DOUBLE PRECISION NOT NULL,
    lon DOUBLE PRECISION NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_on TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_on TIMESTAMP WITHOUT TIME ZONE
);

-- История модерации событий
CREATE TABLE IF NOT EXISTS event_moderation_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT NOT NULL REFERENCES events(id) ON DELETE CASCADE,
    action VARCHAR(20) NOT NULL,
    note VARCHAR(1000),
    acted_on TIMESTAMP WITHOUT TIME ZONE NOT NULL
);

-- Таблица подборок
CREATE TABLE IF NOT EXISTS compilations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(50) NOT NULL,
    pinned BOOLEAN NOT NULL DEFAULT FALSE
);

-- Связь подборок и событий (many-to-many)
CREATE TABLE IF NOT EXISTS compilation_events (
    compilation_id BIGINT NOT NULL REFERENCES compilations(id) ON DELETE CASCADE,
    event_id BIGINT NOT NULL REFERENCES events(id) ON DELETE CASCADE,
    PRIMARY KEY (compilation_id, event_id)
);

-- Индексы
CREATE INDEX IF NOT EXISTS idx_events_category ON events(category_id);
CREATE INDEX IF NOT EXISTS idx_events_initiator ON events(initiator_id);
CREATE INDEX IF NOT EXISTS idx_events_event_date ON events(event_date);
CREATE INDEX IF NOT EXISTS idx_events_state ON events(state);
CREATE UNIQUE INDEX IF NOT EXISTS uq_participation_event_requester
    ON participation_requests(event_id, requester_id);
CREATE INDEX IF NOT EXISTS idx_participation_event ON participation_requests(event_id);
CREATE INDEX IF NOT EXISTS idx_participation_requester ON participation_requests(requester_id);
CREATE INDEX IF NOT EXISTS idx_comments_event_status_created
    ON comments(event_id, status, created_on DESC);
CREATE INDEX IF NOT EXISTS idx_comments_author_created
    ON comments(author_id, created_on DESC);
CREATE INDEX IF NOT EXISTS idx_subscriptions_follower_created
    ON subscriptions(follower_id, created_on DESC);
CREATE INDEX IF NOT EXISTS idx_subscriptions_following_created
    ON subscriptions(following_id, created_on DESC);
CREATE INDEX IF NOT EXISTS idx_event_ratings_event_vote
    ON event_ratings(event_id, vote);
CREATE INDEX IF NOT EXISTS idx_event_ratings_user_updated
    ON event_ratings(user_id, updated_on DESC);
CREATE INDEX IF NOT EXISTS idx_managed_locations_active_created
    ON managed_locations(active, created_on DESC);
CREATE INDEX IF NOT EXISTS idx_event_moderation_logs_event_acted
    ON event_moderation_logs(event_id, acted_on DESC);
CREATE INDEX IF NOT EXISTS idx_compilation_events_event ON compilation_events(event_id);
